name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v3
      - run: yarn install
      - run: yarn test

      
      # Set up QEMU and Docker Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          platforms: linux/amd64

      # Login to the Github Docker Registry
      - name: Login to Github Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ozee-io/fga-transformer-cli

      # Build and push the app container
      - name: Push
        uses: docker/build-push-action@v3
        if: github.event_name != 'pull_request'
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          labels: ${{ steps.metadata-app.outputs.labels }}